name: "homer"
address: "https://kubernetes.default.svc"
values: |
  replicaCount: 1
  selector:
    app.kubernetes.io/name: homer
    app.kubernetes.io/instance: homer
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  loadBalancerIP: 10.0.0.177
